name: test
on: [push]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: install the darknode-cli
              run: |
                  pwd
                  echo $HOME
                  echo $PATH
                  curl https://www.github.com/renproject/darknode-cli/releases/latest/download/install.sh -sSfL | sh
                  pwd




