name: test
on: [push]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Build and install the darknode-cli
              run: |
                  mkdir -p $HOME/.darknode/bin
                  make
                  mv $(make target_name) $HOME/.darknode/bin/darknode
                  export PATH=$PATH:$HOME/.darknode/bin
                  darknode --version





